# Generated by Django 5.0.3 on 2024-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('writer', models.CharField(max_length=60)),
                ('image_relative_url_blog', models.CharField(blank=True, max_length=300, null=True)),
                ('gamename', models.CharField(choices=[('none', 'None'), ('genshin impact', 'Genshin Impact'), ('honkai Starial', 'Honkai Starial'), ('honkai implact3rd', 'Honkai implact3rd'), ('other', 'Other')], default='none', max_length=20)),
                ('mini_description', models.TextField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMesssage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('detial', models.TextField(blank=True, null=True)),
                ('sendtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_relative_url_0', models.CharField(blank=True, max_length=300, null=True)),
                ('image_relative_url_1', models.CharField(blank=True, max_length=300, null=True)),
                ('image_relative_url_2', models.CharField(blank=True, max_length=300, null=True)),
                ('image_relative_url_3', models.CharField(blank=True, max_length=300, null=True)),
                ('image_relative_url_4', models.CharField(blank=True, max_length=300, null=True)),
                ('image_relative_url_5', models.CharField(blank=True, max_length=300, null=True)),
                ('GameName', models.CharField(choices=[('none', 'None'), ('genshin impact', 'Genshin Impact'), ('honkai Starial', 'Honkai Starial'), ('honkai implact3rd', 'Honkai implact3rd')], default='none', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('full_des', models.TextField(blank=True, null=True)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='sub_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
