# Generated by Django 5.0.3 on 2024-03-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_news',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
