# Generated by Django 5.0.3 on 2024-03-21 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_alter_sub_news_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_news',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
