# Generated by Django 5.0.3 on 2024-03-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0003_sub_news_addtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sub_news',
        ),
    ]
