# Generated by Django 5.0.3 on 2024-03-22 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0004_delete_sub_news'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(choices=[(True, 'ชอบ'), (False, 'ไม่ชอบ')], default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_user_pivot_set', to='app_general.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_item_pivot_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_food_set',
            field=models.ManyToManyField(related_name='favorited_user_set', through='users.UserFavoriteitem', to='app_general.item'),
        ),
        migrations.AddConstraint(
            model_name='userfavoriteitem',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='unique_user_food'),
        ),
    ]
