# Generated by Django 5.0.3 on 2024-03-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0004_delete_sub_news'),
        ('users', '0002_userfavoriteitem_customuser_favorite_food_set_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfavoriteitem',
            name='unique_user_food',
        ),
        migrations.AddConstraint(
            model_name='userfavoriteitem',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='unique_user_item'),
        ),
    ]
