# Generated by Django 5.0.3 on 2024-03-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userfavoriteitem_unique_user_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoriteitem',
            name='like',
            field=models.SmallIntegerField(choices=[(1, 'ชอบ'), (2, 'ไม่ชอบ')], default=True),
        ),
    ]
