# Generated by Django 5.0.3 on 2024-03-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userfavoriteitem_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoriteitem',
            name='like',
            field=models.SmallIntegerField(choices=[(1, 'ชอบ')], default=1),
        ),
    ]
